import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ClientLayoutWrapper } from '@/components/layout/ClientLayoutWrapper';
import { TransitionOverlay } from '../components/TransitionOverlay';

import { AnimatedFooter } from "../components/footers/AnimatedFooter"


const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Alif Jovani Safik',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  
  return (
    <html lang="en" className="h-full bg-white">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        <TransitionOverlay />

        <ClientLayoutWrapper>{children}</ClientLayoutWrapper>

        <AnimatedFooter />
      </body>
    </html>
  );
}